public enum UIEnum
{
    None = 0,
    LoadingPanel,
    LoginPanel,
    StartPanel,
    SaveSlotPanel,
    GameMainPanel,
    FinishPanel,
    SettingPanel,
    BagPanel,
    ConfirmPanel,
    ShopPanel,
    EquipPanel,
    CodexPanel,
    TaskPanel,
    MapSelectPanel,
    RewardClaimPanel,
    LeaderboardPanel,
    ItemDescPanel,
}
