// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: hero.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Youzu.Got.Config {

  /// <summary>Holder for reflection information generated from hero.proto</summary>
  public static partial class HeroReflection {

    #region Descriptor
    /// <summary>File descriptor for hero.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HeroReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpoZXJvLnByb3RvEhRjb20ueW91enUuZ290LmNvbmZpZxoUQ29uZmlnQmFz",
            "ZVR5cGUucHJvdG8i6AEKBEhlcm8SEQoJaGVyb19uYW1lGAEgASgJEg8KB2hl",
            "cm9faWQYAiABKA0SCgoCaHAYAyABKAUSCwoDYXRrGAQgASgFEg0KBXNwZWVk",
            "GAUgASgCEg4KBnJhcml0eRgGIAEoDRISCgpza2lsbF9saXN0GAcgAygFEjwK",
            "CmF0dHJfYm9udXMYCCADKAsyKC5jb20ueW91enUuZ290LmNvbmZpZy5LZXlW",
            "YWx1ZVBhaXJTdHJJbnQSMgoIaW5pdF9wb3MYCSABKAsyIC5jb20ueW91enUu",
            "Z290LmNvbmZpZy5WZWN0b3IySW50IkQKF0hlcm9fTElTVF9UT09MX1JFU0VS",
            "VkVEEikKBWl0ZW1zGAEgAygLMhouY29tLnlvdXp1LmdvdC5jb25maWcuSGVy",
            "b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Com.Youzu.Got.Config.ConfigBaseTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Youzu.Got.Config.Hero), global::Com.Youzu.Got.Config.Hero.Parser, new[]{ "HeroName", "HeroId", "Hp", "Atk", "Speed", "Rarity", "SkillList", "AttrBonus", "InitPos" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Youzu.Got.Config.Hero_LIST_TOOL_RESERVED), global::Com.Youzu.Got.Config.Hero_LIST_TOOL_RESERVED.Parser, new[]{ "Items" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Hero : pb::IMessage<Hero> {
    private static readonly pb::MessageParser<Hero> _parser = new pb::MessageParser<Hero>(() => new Hero());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Hero> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Youzu.Got.Config.HeroReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Hero() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Hero(Hero other) : this() {
      heroName_ = other.heroName_;
      heroId_ = other.heroId_;
      hp_ = other.hp_;
      atk_ = other.atk_;
      speed_ = other.speed_;
      rarity_ = other.rarity_;
      skillList_ = other.skillList_.Clone();
      attrBonus_ = other.attrBonus_.Clone();
      initPos_ = other.initPos_ != null ? other.initPos_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Hero Clone() {
      return new Hero(this);
    }

    /// <summary>Field number for the "hero_name" field.</summary>
    public const int HeroNameFieldNumber = 1;
    private string heroName_ = "";
    /// <summary>
    ///英雄名称
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string HeroName {
      get { return heroName_; }
      set {
        heroName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "hero_id" field.</summary>
    public const int HeroIdFieldNumber = 2;
    private uint heroId_;
    /// <summary>
    ///英雄ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint HeroId {
      get { return heroId_; }
      set {
        heroId_ = value;
      }
    }

    /// <summary>Field number for the "hp" field.</summary>
    public const int HpFieldNumber = 3;
    private int hp_;
    /// <summary>
    ///生命值
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Hp {
      get { return hp_; }
      set {
        hp_ = value;
      }
    }

    /// <summary>Field number for the "atk" field.</summary>
    public const int AtkFieldNumber = 4;
    private int atk_;
    /// <summary>
    ///攻击力
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Atk {
      get { return atk_; }
      set {
        atk_ = value;
      }
    }

    /// <summary>Field number for the "speed" field.</summary>
    public const int SpeedFieldNumber = 5;
    private float speed_;
    /// <summary>
    ///速度
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Speed {
      get { return speed_; }
      set {
        speed_ = value;
      }
    }

    /// <summary>Field number for the "rarity" field.</summary>
    public const int RarityFieldNumber = 6;
    private uint rarity_;
    /// <summary>
    ///稀有度
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Rarity {
      get { return rarity_; }
      set {
        rarity_ = value;
      }
    }

    /// <summary>Field number for the "skill_list" field.</summary>
    public const int SkillListFieldNumber = 7;
    private static readonly pb::FieldCodec<int> _repeated_skillList_codec
        = pb::FieldCodec.ForInt32(58);
    private readonly pbc::RepeatedField<int> skillList_ = new pbc::RepeatedField<int>();
    /// <summary>
    ///技能列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> SkillList {
      get { return skillList_; }
    }

    /// <summary>Field number for the "attr_bonus" field.</summary>
    public const int AttrBonusFieldNumber = 8;
    private static readonly pb::FieldCodec<global::Com.Youzu.Got.Config.KeyValuePairStrInt> _repeated_attrBonus_codec
        = pb::FieldCodec.ForMessage(66, global::Com.Youzu.Got.Config.KeyValuePairStrInt.Parser);
    private readonly pbc::RepeatedField<global::Com.Youzu.Got.Config.KeyValuePairStrInt> attrBonus_ = new pbc::RepeatedField<global::Com.Youzu.Got.Config.KeyValuePairStrInt>();
    /// <summary>
    ///属性加成
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Com.Youzu.Got.Config.KeyValuePairStrInt> AttrBonus {
      get { return attrBonus_; }
    }

    /// <summary>Field number for the "init_pos" field.</summary>
    public const int InitPosFieldNumber = 9;
    private global::Com.Youzu.Got.Config.Vector2Int initPos_;
    /// <summary>
    ///初始位置
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Com.Youzu.Got.Config.Vector2Int InitPos {
      get { return initPos_; }
      set {
        initPos_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Hero);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Hero other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (HeroName != other.HeroName) return false;
      if (HeroId != other.HeroId) return false;
      if (Hp != other.Hp) return false;
      if (Atk != other.Atk) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Speed, other.Speed)) return false;
      if (Rarity != other.Rarity) return false;
      if(!skillList_.Equals(other.skillList_)) return false;
      if(!attrBonus_.Equals(other.attrBonus_)) return false;
      if (!object.Equals(InitPos, other.InitPos)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HeroName.Length != 0) hash ^= HeroName.GetHashCode();
      if (HeroId != 0) hash ^= HeroId.GetHashCode();
      if (Hp != 0) hash ^= Hp.GetHashCode();
      if (Atk != 0) hash ^= Atk.GetHashCode();
      if (Speed != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Speed);
      if (Rarity != 0) hash ^= Rarity.GetHashCode();
      hash ^= skillList_.GetHashCode();
      hash ^= attrBonus_.GetHashCode();
      if (initPos_ != null) hash ^= InitPos.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (HeroName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(HeroName);
      }
      if (HeroId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(HeroId);
      }
      if (Hp != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Hp);
      }
      if (Atk != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Atk);
      }
      if (Speed != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(Speed);
      }
      if (Rarity != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(Rarity);
      }
      skillList_.WriteTo(output, _repeated_skillList_codec);
      attrBonus_.WriteTo(output, _repeated_attrBonus_codec);
      if (initPos_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(InitPos);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HeroName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(HeroName);
      }
      if (HeroId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HeroId);
      }
      if (Hp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Hp);
      }
      if (Atk != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Atk);
      }
      if (Speed != 0F) {
        size += 1 + 4;
      }
      if (Rarity != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Rarity);
      }
      size += skillList_.CalculateSize(_repeated_skillList_codec);
      size += attrBonus_.CalculateSize(_repeated_attrBonus_codec);
      if (initPos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InitPos);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Hero other) {
      if (other == null) {
        return;
      }
      if (other.HeroName.Length != 0) {
        HeroName = other.HeroName;
      }
      if (other.HeroId != 0) {
        HeroId = other.HeroId;
      }
      if (other.Hp != 0) {
        Hp = other.Hp;
      }
      if (other.Atk != 0) {
        Atk = other.Atk;
      }
      if (other.Speed != 0F) {
        Speed = other.Speed;
      }
      if (other.Rarity != 0) {
        Rarity = other.Rarity;
      }
      skillList_.Add(other.skillList_);
      attrBonus_.Add(other.attrBonus_);
      if (other.initPos_ != null) {
        if (initPos_ == null) {
          initPos_ = new global::Com.Youzu.Got.Config.Vector2Int();
        }
        InitPos.MergeFrom(other.InitPos);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            HeroName = input.ReadString();
            break;
          }
          case 16: {
            HeroId = input.ReadUInt32();
            break;
          }
          case 24: {
            Hp = input.ReadInt32();
            break;
          }
          case 32: {
            Atk = input.ReadInt32();
            break;
          }
          case 45: {
            Speed = input.ReadFloat();
            break;
          }
          case 48: {
            Rarity = input.ReadUInt32();
            break;
          }
          case 58:
          case 56: {
            skillList_.AddEntriesFrom(input, _repeated_skillList_codec);
            break;
          }
          case 66: {
            attrBonus_.AddEntriesFrom(input, _repeated_attrBonus_codec);
            break;
          }
          case 74: {
            if (initPos_ == null) {
              initPos_ = new global::Com.Youzu.Got.Config.Vector2Int();
            }
            input.ReadMessage(initPos_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Hero_LIST_TOOL_RESERVED : pb::IMessage<Hero_LIST_TOOL_RESERVED> {
    private static readonly pb::MessageParser<Hero_LIST_TOOL_RESERVED> _parser = new pb::MessageParser<Hero_LIST_TOOL_RESERVED>(() => new Hero_LIST_TOOL_RESERVED());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Hero_LIST_TOOL_RESERVED> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Youzu.Got.Config.HeroReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Hero_LIST_TOOL_RESERVED() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Hero_LIST_TOOL_RESERVED(Hero_LIST_TOOL_RESERVED other) : this() {
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Hero_LIST_TOOL_RESERVED Clone() {
      return new Hero_LIST_TOOL_RESERVED(this);
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Com.Youzu.Got.Config.Hero> _repeated_items_codec
        = pb::FieldCodec.ForMessage(10, global::Com.Youzu.Got.Config.Hero.Parser);
    private readonly pbc::RepeatedField<global::Com.Youzu.Got.Config.Hero> items_ = new pbc::RepeatedField<global::Com.Youzu.Got.Config.Hero>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Com.Youzu.Got.Config.Hero> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Hero_LIST_TOOL_RESERVED);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Hero_LIST_TOOL_RESERVED other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!items_.Equals(other.items_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= items_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      items_.WriteTo(output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_repeated_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Hero_LIST_TOOL_RESERVED other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
