// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: item.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace YFramework.Config {

  /// <summary>Holder for reflection information generated from item.proto</summary>
  public static partial class ItemReflection {

    #region Descriptor
    /// <summary>File descriptor for item.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ItemReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgppdGVtLnByb3RvEhF5ZnJhbWV3b3JrLmNvbmZpZxoUQ29uZmlnQmFzZVR5",
            "cGUucHJvdG8ipQIKBEl0ZW0SCgoCaWQYASABKA0SDAoEbmFtZRgCIAEoCRIM",
            "CgRkZXNjGAMgASgJEgwKBHR5cGUYBCABKA0SDwoHcXVhbGl0eRgFIAEoDRIQ",
            "CghpY29uUGF0aBgGIAEoCRINCgV3aWR0aBgHIAEoBRIOCgZoZWlnaHQYCCAB",
            "KAUSDQoFc2hhcGUYCSABKAkSEAoIbWF4U3RhY2sYCiABKAUSDQoFdmFsdWUY",
            "CyABKAUSFAoMc29ydFByaW9yaXR5GAwgASgFEhEKCXByaWNlVHlwZRgNIAEo",
            "DRINCgVwcmljZRgOIAEoBRIUCgxzaG9wQ2F0ZWdvcnkYDyABKA0SEQoJbW9k",
            "ZWxQYXRoGBAgASgJEhQKDGRpc3R1cmJSYW5nZRgRIAEoBSJBChdJdGVtX0xJ",
            "U1RfVE9PTF9SRVNFUlZFRBImCgVpdGVtcxgBIAMoCzIXLnlmcmFtZXdvcmsu",
            "Y29uZmlnLkl0ZW1CFKoCEVlGcmFtZXdvcmsuQ29uZmlnYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::YFramework.Config.ConfigBaseTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::YFramework.Config.Item), global::YFramework.Config.Item.Parser, new[]{ "Id", "Name", "Desc", "Type", "Quality", "IconPath", "Width", "Height", "Shape", "MaxStack", "Value", "SortPriority", "PriceType", "Price", "ShopCategory", "ModelPath", "DisturbRange" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::YFramework.Config.Item_LIST_TOOL_RESERVED), global::YFramework.Config.Item_LIST_TOOL_RESERVED.Parser, new[]{ "Items" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Item : pb::IMessage<Item> {
    private static readonly pb::MessageParser<Item> _parser = new pb::MessageParser<Item>(() => new Item());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Item> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::YFramework.Config.ItemReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Item() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Item(Item other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      desc_ = other.desc_;
      type_ = other.type_;
      quality_ = other.quality_;
      iconPath_ = other.iconPath_;
      width_ = other.width_;
      height_ = other.height_;
      shape_ = other.shape_;
      maxStack_ = other.maxStack_;
      value_ = other.value_;
      sortPriority_ = other.sortPriority_;
      priceType_ = other.priceType_;
      price_ = other.price_;
      shopCategory_ = other.shopCategory_;
      modelPath_ = other.modelPath_;
      disturbRange_ = other.disturbRange_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Item Clone() {
      return new Item(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private uint id_;
    /// <summary>
    ///物品ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    /// <summary>
    ///名称
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "desc" field.</summary>
    public const int DescFieldNumber = 3;
    private string desc_ = "";
    /// <summary>
    ///描述
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Desc {
      get { return desc_; }
      set {
        desc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 4;
    private uint type_;
    /// <summary>
    ///类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "quality" field.</summary>
    public const int QualityFieldNumber = 5;
    private uint quality_;
    /// <summary>
    ///品质
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Quality {
      get { return quality_; }
      set {
        quality_ = value;
      }
    }

    /// <summary>Field number for the "iconPath" field.</summary>
    public const int IconPathFieldNumber = 6;
    private string iconPath_ = "";
    /// <summary>
    ///图标路径
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IconPath {
      get { return iconPath_; }
      set {
        iconPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "width" field.</summary>
    public const int WidthFieldNumber = 7;
    private int width_;
    /// <summary>
    ///占格宽
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Width {
      get { return width_; }
      set {
        width_ = value;
      }
    }

    /// <summary>Field number for the "height" field.</summary>
    public const int HeightFieldNumber = 8;
    private int height_;
    /// <summary>
    ///占格高
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Height {
      get { return height_; }
      set {
        height_ = value;
      }
    }

    /// <summary>Field number for the "shape" field.</summary>
    public const int ShapeFieldNumber = 9;
    private string shape_ = "";
    /// <summary>
    ///形状掩码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Shape {
      get { return shape_; }
      set {
        shape_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "maxStack" field.</summary>
    public const int MaxStackFieldNumber = 10;
    private int maxStack_;
    /// <summary>
    ///叠加上限
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MaxStack {
      get { return maxStack_; }
      set {
        maxStack_ = value;
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 11;
    private int value_;
    /// <summary>
    ///预估价值
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    /// <summary>Field number for the "sortPriority" field.</summary>
    public const int SortPriorityFieldNumber = 12;
    private int sortPriority_;
    /// <summary>
    ///排序权重
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SortPriority {
      get { return sortPriority_; }
      set {
        sortPriority_ = value;
      }
    }

    /// <summary>Field number for the "priceType" field.</summary>
    public const int PriceTypeFieldNumber = 13;
    private uint priceType_;
    /// <summary>
    ///购买货币
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint PriceType {
      get { return priceType_; }
      set {
        priceType_ = value;
      }
    }

    /// <summary>Field number for the "price" field.</summary>
    public const int PriceFieldNumber = 14;
    private int price_;
    /// <summary>
    ///购买价格
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Price {
      get { return price_; }
      set {
        price_ = value;
      }
    }

    /// <summary>Field number for the "shopCategory" field.</summary>
    public const int ShopCategoryFieldNumber = 15;
    private uint shopCategory_;
    /// <summary>
    ///商店分类
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ShopCategory {
      get { return shopCategory_; }
      set {
        shopCategory_ = value;
      }
    }

    /// <summary>Field number for the "modelPath" field.</summary>
    public const int ModelPathFieldNumber = 16;
    private string modelPath_ = "";
    /// <summary>
    ///模型路径
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ModelPath {
      get { return modelPath_; }
      set {
        modelPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "disturbRange" field.</summary>
    public const int DisturbRangeFieldNumber = 17;
    private int disturbRange_;
    /// <summary>
    ///惊扰范围
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DisturbRange {
      get { return disturbRange_; }
      set {
        disturbRange_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Item);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Item other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (Desc != other.Desc) return false;
      if (Type != other.Type) return false;
      if (Quality != other.Quality) return false;
      if (IconPath != other.IconPath) return false;
      if (Width != other.Width) return false;
      if (Height != other.Height) return false;
      if (Shape != other.Shape) return false;
      if (MaxStack != other.MaxStack) return false;
      if (Value != other.Value) return false;
      if (SortPriority != other.SortPriority) return false;
      if (PriceType != other.PriceType) return false;
      if (Price != other.Price) return false;
      if (ShopCategory != other.ShopCategory) return false;
      if (ModelPath != other.ModelPath) return false;
      if (DisturbRange != other.DisturbRange) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Desc.Length != 0) hash ^= Desc.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (Quality != 0) hash ^= Quality.GetHashCode();
      if (IconPath.Length != 0) hash ^= IconPath.GetHashCode();
      if (Width != 0) hash ^= Width.GetHashCode();
      if (Height != 0) hash ^= Height.GetHashCode();
      if (Shape.Length != 0) hash ^= Shape.GetHashCode();
      if (MaxStack != 0) hash ^= MaxStack.GetHashCode();
      if (Value != 0) hash ^= Value.GetHashCode();
      if (SortPriority != 0) hash ^= SortPriority.GetHashCode();
      if (PriceType != 0) hash ^= PriceType.GetHashCode();
      if (Price != 0) hash ^= Price.GetHashCode();
      if (ShopCategory != 0) hash ^= ShopCategory.GetHashCode();
      if (ModelPath.Length != 0) hash ^= ModelPath.GetHashCode();
      if (DisturbRange != 0) hash ^= DisturbRange.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Desc.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Desc);
      }
      if (Type != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Type);
      }
      if (Quality != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Quality);
      }
      if (IconPath.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(IconPath);
      }
      if (Width != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Width);
      }
      if (Height != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Height);
      }
      if (Shape.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Shape);
      }
      if (MaxStack != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(MaxStack);
      }
      if (Value != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(Value);
      }
      if (SortPriority != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(SortPriority);
      }
      if (PriceType != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(PriceType);
      }
      if (Price != 0) {
        output.WriteRawTag(112);
        output.WriteInt32(Price);
      }
      if (ShopCategory != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(ShopCategory);
      }
      if (ModelPath.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(ModelPath);
      }
      if (DisturbRange != 0) {
        output.WriteRawTag(136, 1);
        output.WriteInt32(DisturbRange);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Desc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Desc);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Type);
      }
      if (Quality != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Quality);
      }
      if (IconPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IconPath);
      }
      if (Width != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Width);
      }
      if (Height != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Height);
      }
      if (Shape.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Shape);
      }
      if (MaxStack != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxStack);
      }
      if (Value != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Value);
      }
      if (SortPriority != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SortPriority);
      }
      if (PriceType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PriceType);
      }
      if (Price != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Price);
      }
      if (ShopCategory != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ShopCategory);
      }
      if (ModelPath.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ModelPath);
      }
      if (DisturbRange != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(DisturbRange);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Item other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Desc.Length != 0) {
        Desc = other.Desc;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.Quality != 0) {
        Quality = other.Quality;
      }
      if (other.IconPath.Length != 0) {
        IconPath = other.IconPath;
      }
      if (other.Width != 0) {
        Width = other.Width;
      }
      if (other.Height != 0) {
        Height = other.Height;
      }
      if (other.Shape.Length != 0) {
        Shape = other.Shape;
      }
      if (other.MaxStack != 0) {
        MaxStack = other.MaxStack;
      }
      if (other.Value != 0) {
        Value = other.Value;
      }
      if (other.SortPriority != 0) {
        SortPriority = other.SortPriority;
      }
      if (other.PriceType != 0) {
        PriceType = other.PriceType;
      }
      if (other.Price != 0) {
        Price = other.Price;
      }
      if (other.ShopCategory != 0) {
        ShopCategory = other.ShopCategory;
      }
      if (other.ModelPath.Length != 0) {
        ModelPath = other.ModelPath;
      }
      if (other.DisturbRange != 0) {
        DisturbRange = other.DisturbRange;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadUInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Desc = input.ReadString();
            break;
          }
          case 32: {
            Type = input.ReadUInt32();
            break;
          }
          case 40: {
            Quality = input.ReadUInt32();
            break;
          }
          case 50: {
            IconPath = input.ReadString();
            break;
          }
          case 56: {
            Width = input.ReadInt32();
            break;
          }
          case 64: {
            Height = input.ReadInt32();
            break;
          }
          case 74: {
            Shape = input.ReadString();
            break;
          }
          case 80: {
            MaxStack = input.ReadInt32();
            break;
          }
          case 88: {
            Value = input.ReadInt32();
            break;
          }
          case 96: {
            SortPriority = input.ReadInt32();
            break;
          }
          case 104: {
            PriceType = input.ReadUInt32();
            break;
          }
          case 112: {
            Price = input.ReadInt32();
            break;
          }
          case 120: {
            ShopCategory = input.ReadUInt32();
            break;
          }
          case 130: {
            ModelPath = input.ReadString();
            break;
          }
          case 136: {
            DisturbRange = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Item_LIST_TOOL_RESERVED : pb::IMessage<Item_LIST_TOOL_RESERVED> {
    private static readonly pb::MessageParser<Item_LIST_TOOL_RESERVED> _parser = new pb::MessageParser<Item_LIST_TOOL_RESERVED>(() => new Item_LIST_TOOL_RESERVED());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Item_LIST_TOOL_RESERVED> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::YFramework.Config.ItemReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Item_LIST_TOOL_RESERVED() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Item_LIST_TOOL_RESERVED(Item_LIST_TOOL_RESERVED other) : this() {
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Item_LIST_TOOL_RESERVED Clone() {
      return new Item_LIST_TOOL_RESERVED(this);
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::YFramework.Config.Item> _repeated_items_codec
        = pb::FieldCodec.ForMessage(10, global::YFramework.Config.Item.Parser);
    private readonly pbc::RepeatedField<global::YFramework.Config.Item> items_ = new pbc::RepeatedField<global::YFramework.Config.Item>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::YFramework.Config.Item> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Item_LIST_TOOL_RESERVED);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Item_LIST_TOOL_RESERVED other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!items_.Equals(other.items_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= items_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      items_.WriteTo(output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_repeated_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Item_LIST_TOOL_RESERVED other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
