// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: level.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace YFramework.Config {

  /// <summary>Holder for reflection information generated from level.proto</summary>
  public static partial class LevelReflection {

    #region Descriptor
    /// <summary>File descriptor for level.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LevelReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtsZXZlbC5wcm90bxIReWZyYW1ld29yay5jb25maWcaFENvbmZpZ0Jhc2VU",
            "eXBlLnByb3RvIr0BCgVMZXZlbBIKCgJpZBgBIAEoDRIRCglkaXNwbGF5SWQY",
            "AiABKAkSDAoEbmFtZRgDIAEoCRITCgtkZXNjcmlwdGlvbhgEIAEoCRIWCg5y",
            "ZWNvbW1lbmRMZXZlbBgFIAEoBRIVCg1zY2VuZUFzc2V0S2V5GAYgASgJEhQK",
            "DHByZXJlcXVpc2l0ZRgHIAMoDRIMCgRwb3NYGAggASgCEgwKBHBvc1kYCSAB",
            "KAISEQoJdGltZTNTdGFyGAogASgFIkMKGExldmVsX0xJU1RfVE9PTF9SRVNF",
            "UlZFRBInCgVpdGVtcxgBIAMoCzIYLnlmcmFtZXdvcmsuY29uZmlnLkxldmVs",
            "QhSqAhFZRnJhbWV3b3JrLkNvbmZpZ2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::YFramework.Config.ConfigBaseTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::YFramework.Config.Level), global::YFramework.Config.Level.Parser, new[]{ "Id", "DisplayId", "Name", "Description", "RecommendLevel", "SceneAssetKey", "Prerequisite", "PosX", "PosY", "Time3Star" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::YFramework.Config.Level_LIST_TOOL_RESERVED), global::YFramework.Config.Level_LIST_TOOL_RESERVED.Parser, new[]{ "Items" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Level : pb::IMessage<Level> {
    private static readonly pb::MessageParser<Level> _parser = new pb::MessageParser<Level>(() => new Level());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Level> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::YFramework.Config.LevelReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Level() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Level(Level other) : this() {
      id_ = other.id_;
      displayId_ = other.displayId_;
      name_ = other.name_;
      description_ = other.description_;
      recommendLevel_ = other.recommendLevel_;
      sceneAssetKey_ = other.sceneAssetKey_;
      prerequisite_ = other.prerequisite_.Clone();
      posX_ = other.posX_;
      posY_ = other.posY_;
      time3Star_ = other.time3Star_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Level Clone() {
      return new Level(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private uint id_;
    /// <summary>
    ///关卡ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "displayId" field.</summary>
    public const int DisplayIdFieldNumber = 2;
    private string displayId_ = "";
    /// <summary>
    ///显示编号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DisplayId {
      get { return displayId_; }
      set {
        displayId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    /// <summary>
    ///关卡名
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 4;
    private string description_ = "";
    /// <summary>
    ///描述
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "recommendLevel" field.</summary>
    public const int RecommendLevelFieldNumber = 5;
    private int recommendLevel_;
    /// <summary>
    ///推荐等级
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RecommendLevel {
      get { return recommendLevel_; }
      set {
        recommendLevel_ = value;
      }
    }

    /// <summary>Field number for the "sceneAssetKey" field.</summary>
    public const int SceneAssetKeyFieldNumber = 6;
    private string sceneAssetKey_ = "";
    /// <summary>
    ///场景资源Key
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SceneAssetKey {
      get { return sceneAssetKey_; }
      set {
        sceneAssetKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "prerequisite" field.</summary>
    public const int PrerequisiteFieldNumber = 7;
    private static readonly pb::FieldCodec<uint> _repeated_prerequisite_codec
        = pb::FieldCodec.ForUInt32(58);
    private readonly pbc::RepeatedField<uint> prerequisite_ = new pbc::RepeatedField<uint>();
    /// <summary>
    ///前置关卡
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<uint> Prerequisite {
      get { return prerequisite_; }
    }

    /// <summary>Field number for the "posX" field.</summary>
    public const int PosXFieldNumber = 8;
    private float posX_;
    /// <summary>
    ///地图X坐标
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float PosX {
      get { return posX_; }
      set {
        posX_ = value;
      }
    }

    /// <summary>Field number for the "posY" field.</summary>
    public const int PosYFieldNumber = 9;
    private float posY_;
    /// <summary>
    ///地图Y坐标
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float PosY {
      get { return posY_; }
      set {
        posY_ = value;
      }
    }

    /// <summary>Field number for the "time3Star" field.</summary>
    public const int Time3StarFieldNumber = 10;
    private int time3Star_;
    /// <summary>
    ///3星耗时阈值秒
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Time3Star {
      get { return time3Star_; }
      set {
        time3Star_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Level);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Level other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (DisplayId != other.DisplayId) return false;
      if (Name != other.Name) return false;
      if (Description != other.Description) return false;
      if (RecommendLevel != other.RecommendLevel) return false;
      if (SceneAssetKey != other.SceneAssetKey) return false;
      if(!prerequisite_.Equals(other.prerequisite_)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PosX, other.PosX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PosY, other.PosY)) return false;
      if (Time3Star != other.Time3Star) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (DisplayId.Length != 0) hash ^= DisplayId.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (RecommendLevel != 0) hash ^= RecommendLevel.GetHashCode();
      if (SceneAssetKey.Length != 0) hash ^= SceneAssetKey.GetHashCode();
      hash ^= prerequisite_.GetHashCode();
      if (PosX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PosX);
      if (PosY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PosY);
      if (Time3Star != 0) hash ^= Time3Star.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Id);
      }
      if (DisplayId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DisplayId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Description);
      }
      if (RecommendLevel != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(RecommendLevel);
      }
      if (SceneAssetKey.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(SceneAssetKey);
      }
      prerequisite_.WriteTo(output, _repeated_prerequisite_codec);
      if (PosX != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(PosX);
      }
      if (PosY != 0F) {
        output.WriteRawTag(77);
        output.WriteFloat(PosY);
      }
      if (Time3Star != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(Time3Star);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
      }
      if (DisplayId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DisplayId);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (RecommendLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RecommendLevel);
      }
      if (SceneAssetKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SceneAssetKey);
      }
      size += prerequisite_.CalculateSize(_repeated_prerequisite_codec);
      if (PosX != 0F) {
        size += 1 + 4;
      }
      if (PosY != 0F) {
        size += 1 + 4;
      }
      if (Time3Star != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Time3Star);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Level other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.DisplayId.Length != 0) {
        DisplayId = other.DisplayId;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      if (other.RecommendLevel != 0) {
        RecommendLevel = other.RecommendLevel;
      }
      if (other.SceneAssetKey.Length != 0) {
        SceneAssetKey = other.SceneAssetKey;
      }
      prerequisite_.Add(other.prerequisite_);
      if (other.PosX != 0F) {
        PosX = other.PosX;
      }
      if (other.PosY != 0F) {
        PosY = other.PosY;
      }
      if (other.Time3Star != 0) {
        Time3Star = other.Time3Star;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadUInt32();
            break;
          }
          case 18: {
            DisplayId = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            Description = input.ReadString();
            break;
          }
          case 40: {
            RecommendLevel = input.ReadInt32();
            break;
          }
          case 50: {
            SceneAssetKey = input.ReadString();
            break;
          }
          case 58:
          case 56: {
            prerequisite_.AddEntriesFrom(input, _repeated_prerequisite_codec);
            break;
          }
          case 69: {
            PosX = input.ReadFloat();
            break;
          }
          case 77: {
            PosY = input.ReadFloat();
            break;
          }
          case 80: {
            Time3Star = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Level_LIST_TOOL_RESERVED : pb::IMessage<Level_LIST_TOOL_RESERVED> {
    private static readonly pb::MessageParser<Level_LIST_TOOL_RESERVED> _parser = new pb::MessageParser<Level_LIST_TOOL_RESERVED>(() => new Level_LIST_TOOL_RESERVED());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Level_LIST_TOOL_RESERVED> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::YFramework.Config.LevelReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Level_LIST_TOOL_RESERVED() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Level_LIST_TOOL_RESERVED(Level_LIST_TOOL_RESERVED other) : this() {
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Level_LIST_TOOL_RESERVED Clone() {
      return new Level_LIST_TOOL_RESERVED(this);
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::YFramework.Config.Level> _repeated_items_codec
        = pb::FieldCodec.ForMessage(10, global::YFramework.Config.Level.Parser);
    private readonly pbc::RepeatedField<global::YFramework.Config.Level> items_ = new pbc::RepeatedField<global::YFramework.Config.Level>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::YFramework.Config.Level> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Level_LIST_TOOL_RESERVED);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Level_LIST_TOOL_RESERVED other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!items_.Equals(other.items_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= items_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      items_.WriteTo(output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_repeated_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Level_LIST_TOOL_RESERVED other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
