// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: map.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace YFramework.Config {

  /// <summary>Holder for reflection information generated from map.proto</summary>
  public static partial class MapReflection {

    #region Descriptor
    /// <summary>File descriptor for map.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MapReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgltYXAucHJvdG8SEXlmcmFtZXdvcmsuY29uZmlnGhRDb25maWdCYXNlVHlw",
            "ZS5wcm90byJ9CgNNYXASCgoCaWQYASABKA0SDAoEbmFtZRgCIAEoCRIQCghp",
            "Y29uUGF0aBgDIAEoCRIQCgh1bmxvY2tlZBgEIAEoBRIUCgxzb3J0UHJpb3Jp",
            "dHkYBSABKAUSDwoHYW5pbWFscxgGIAMoDRIRCglzY2VuZVBhdGgYByABKAki",
            "PwoWTWFwX0xJU1RfVE9PTF9SRVNFUlZFRBIlCgVpdGVtcxgBIAMoCzIWLnlm",
            "cmFtZXdvcmsuY29uZmlnLk1hcEIUqgIRWUZyYW1ld29yay5Db25maWdiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::YFramework.Config.ConfigBaseTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::YFramework.Config.Map), global::YFramework.Config.Map.Parser, new[]{ "Id", "Name", "IconPath", "Unlocked", "SortPriority", "Animals", "ScenePath" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::YFramework.Config.Map_LIST_TOOL_RESERVED), global::YFramework.Config.Map_LIST_TOOL_RESERVED.Parser, new[]{ "Items" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Map : pb::IMessage<Map> {
    private static readonly pb::MessageParser<Map> _parser = new pb::MessageParser<Map>(() => new Map());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Map> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::YFramework.Config.MapReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Map() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Map(Map other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      iconPath_ = other.iconPath_;
      unlocked_ = other.unlocked_;
      sortPriority_ = other.sortPriority_;
      animals_ = other.animals_.Clone();
      scenePath_ = other.scenePath_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Map Clone() {
      return new Map(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private uint id_;
    /// <summary>
    ///关卡ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    /// <summary>
    ///名称
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "iconPath" field.</summary>
    public const int IconPathFieldNumber = 3;
    private string iconPath_ = "";
    /// <summary>
    ///预览图
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IconPath {
      get { return iconPath_; }
      set {
        iconPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "unlocked" field.</summary>
    public const int UnlockedFieldNumber = 4;
    private int unlocked_;
    /// <summary>
    ///是否解锁
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Unlocked {
      get { return unlocked_; }
      set {
        unlocked_ = value;
      }
    }

    /// <summary>Field number for the "sortPriority" field.</summary>
    public const int SortPriorityFieldNumber = 5;
    private int sortPriority_;
    /// <summary>
    ///排序权重
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SortPriority {
      get { return sortPriority_; }
      set {
        sortPriority_ = value;
      }
    }

    /// <summary>Field number for the "animals" field.</summary>
    public const int AnimalsFieldNumber = 6;
    private static readonly pb::FieldCodec<uint> _repeated_animals_codec
        = pb::FieldCodec.ForUInt32(50);
    private readonly pbc::RepeatedField<uint> animals_ = new pbc::RepeatedField<uint>();
    /// <summary>
    ///动物池
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<uint> Animals {
      get { return animals_; }
    }

    /// <summary>Field number for the "scenePath" field.</summary>
    public const int ScenePathFieldNumber = 7;
    private string scenePath_ = "";
    /// <summary>
    ///场景预制体
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ScenePath {
      get { return scenePath_; }
      set {
        scenePath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Map);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Map other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (IconPath != other.IconPath) return false;
      if (Unlocked != other.Unlocked) return false;
      if (SortPriority != other.SortPriority) return false;
      if(!animals_.Equals(other.animals_)) return false;
      if (ScenePath != other.ScenePath) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (IconPath.Length != 0) hash ^= IconPath.GetHashCode();
      if (Unlocked != 0) hash ^= Unlocked.GetHashCode();
      if (SortPriority != 0) hash ^= SortPriority.GetHashCode();
      hash ^= animals_.GetHashCode();
      if (ScenePath.Length != 0) hash ^= ScenePath.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (IconPath.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(IconPath);
      }
      if (Unlocked != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Unlocked);
      }
      if (SortPriority != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(SortPriority);
      }
      animals_.WriteTo(output, _repeated_animals_codec);
      if (ScenePath.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ScenePath);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (IconPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IconPath);
      }
      if (Unlocked != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Unlocked);
      }
      if (SortPriority != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SortPriority);
      }
      size += animals_.CalculateSize(_repeated_animals_codec);
      if (ScenePath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ScenePath);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Map other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.IconPath.Length != 0) {
        IconPath = other.IconPath;
      }
      if (other.Unlocked != 0) {
        Unlocked = other.Unlocked;
      }
      if (other.SortPriority != 0) {
        SortPriority = other.SortPriority;
      }
      animals_.Add(other.animals_);
      if (other.ScenePath.Length != 0) {
        ScenePath = other.ScenePath;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadUInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            IconPath = input.ReadString();
            break;
          }
          case 32: {
            Unlocked = input.ReadInt32();
            break;
          }
          case 40: {
            SortPriority = input.ReadInt32();
            break;
          }
          case 50:
          case 48: {
            animals_.AddEntriesFrom(input, _repeated_animals_codec);
            break;
          }
          case 58: {
            ScenePath = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Map_LIST_TOOL_RESERVED : pb::IMessage<Map_LIST_TOOL_RESERVED> {
    private static readonly pb::MessageParser<Map_LIST_TOOL_RESERVED> _parser = new pb::MessageParser<Map_LIST_TOOL_RESERVED>(() => new Map_LIST_TOOL_RESERVED());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Map_LIST_TOOL_RESERVED> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::YFramework.Config.MapReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Map_LIST_TOOL_RESERVED() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Map_LIST_TOOL_RESERVED(Map_LIST_TOOL_RESERVED other) : this() {
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Map_LIST_TOOL_RESERVED Clone() {
      return new Map_LIST_TOOL_RESERVED(this);
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::YFramework.Config.Map> _repeated_items_codec
        = pb::FieldCodec.ForMessage(10, global::YFramework.Config.Map.Parser);
    private readonly pbc::RepeatedField<global::YFramework.Config.Map> items_ = new pbc::RepeatedField<global::YFramework.Config.Map>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::YFramework.Config.Map> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Map_LIST_TOOL_RESERVED);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Map_LIST_TOOL_RESERVED other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!items_.Equals(other.items_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= items_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      items_.WriteTo(output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_repeated_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Map_LIST_TOOL_RESERVED other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
