// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: quest.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Youzu.Got.Config {

  /// <summary>Holder for reflection information generated from quest.proto</summary>
  public static partial class QuestReflection {

    #region Descriptor
    /// <summary>File descriptor for quest.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QuestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtxdWVzdC5wcm90bxIUY29tLnlvdXp1LmdvdC5jb25maWcaFENvbmZpZ0Jh",
            "c2VUeXBlLnByb3RvIlwKBVF1ZXN0EhIKCnF1ZXN0X25hbWUYASABKAkSEAoI",
            "cXVlc3RfaWQYAiABKA0SDwoHc3RlcF9pZBgDIAEoDRIMCgRkZXNjGAQgASgJ",
            "Eg4KBnJld2FyZBgFIAEoBSJGChhRdWVzdF9MSVNUX1RPT0xfUkVTRVJWRUQS",
            "KgoFaXRlbXMYASADKAsyGy5jb20ueW91enUuZ290LmNvbmZpZy5RdWVzdGIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Com.Youzu.Got.Config.ConfigBaseTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Youzu.Got.Config.Quest), global::Com.Youzu.Got.Config.Quest.Parser, new[]{ "QuestName", "QuestId", "StepId", "Desc", "Reward" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Youzu.Got.Config.Quest_LIST_TOOL_RESERVED), global::Com.Youzu.Got.Config.Quest_LIST_TOOL_RESERVED.Parser, new[]{ "Items" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Quest : pb::IMessage<Quest> {
    private static readonly pb::MessageParser<Quest> _parser = new pb::MessageParser<Quest>(() => new Quest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Quest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Youzu.Got.Config.QuestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Quest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Quest(Quest other) : this() {
      questName_ = other.questName_;
      questId_ = other.questId_;
      stepId_ = other.stepId_;
      desc_ = other.desc_;
      reward_ = other.reward_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Quest Clone() {
      return new Quest(this);
    }

    /// <summary>Field number for the "quest_name" field.</summary>
    public const int QuestNameFieldNumber = 1;
    private string questName_ = "";
    /// <summary>
    ///任务名
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string QuestName {
      get { return questName_; }
      set {
        questName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "quest_id" field.</summary>
    public const int QuestIdFieldNumber = 2;
    private uint questId_;
    /// <summary>
    ///任务ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint QuestId {
      get { return questId_; }
      set {
        questId_ = value;
      }
    }

    /// <summary>Field number for the "step_id" field.</summary>
    public const int StepIdFieldNumber = 3;
    private uint stepId_;
    /// <summary>
    ///步骤ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint StepId {
      get { return stepId_; }
      set {
        stepId_ = value;
      }
    }

    /// <summary>Field number for the "desc" field.</summary>
    public const int DescFieldNumber = 4;
    private string desc_ = "";
    /// <summary>
    ///描述
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Desc {
      get { return desc_; }
      set {
        desc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "reward" field.</summary>
    public const int RewardFieldNumber = 5;
    private int reward_;
    /// <summary>
    ///奖励
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Reward {
      get { return reward_; }
      set {
        reward_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Quest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Quest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (QuestName != other.QuestName) return false;
      if (QuestId != other.QuestId) return false;
      if (StepId != other.StepId) return false;
      if (Desc != other.Desc) return false;
      if (Reward != other.Reward) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (QuestName.Length != 0) hash ^= QuestName.GetHashCode();
      if (QuestId != 0) hash ^= QuestId.GetHashCode();
      if (StepId != 0) hash ^= StepId.GetHashCode();
      if (Desc.Length != 0) hash ^= Desc.GetHashCode();
      if (Reward != 0) hash ^= Reward.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (QuestName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(QuestName);
      }
      if (QuestId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(QuestId);
      }
      if (StepId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(StepId);
      }
      if (Desc.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Desc);
      }
      if (Reward != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Reward);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (QuestName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(QuestName);
      }
      if (QuestId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(QuestId);
      }
      if (StepId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(StepId);
      }
      if (Desc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Desc);
      }
      if (Reward != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Reward);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Quest other) {
      if (other == null) {
        return;
      }
      if (other.QuestName.Length != 0) {
        QuestName = other.QuestName;
      }
      if (other.QuestId != 0) {
        QuestId = other.QuestId;
      }
      if (other.StepId != 0) {
        StepId = other.StepId;
      }
      if (other.Desc.Length != 0) {
        Desc = other.Desc;
      }
      if (other.Reward != 0) {
        Reward = other.Reward;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            QuestName = input.ReadString();
            break;
          }
          case 16: {
            QuestId = input.ReadUInt32();
            break;
          }
          case 24: {
            StepId = input.ReadUInt32();
            break;
          }
          case 34: {
            Desc = input.ReadString();
            break;
          }
          case 40: {
            Reward = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Quest_LIST_TOOL_RESERVED : pb::IMessage<Quest_LIST_TOOL_RESERVED> {
    private static readonly pb::MessageParser<Quest_LIST_TOOL_RESERVED> _parser = new pb::MessageParser<Quest_LIST_TOOL_RESERVED>(() => new Quest_LIST_TOOL_RESERVED());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Quest_LIST_TOOL_RESERVED> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Youzu.Got.Config.QuestReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Quest_LIST_TOOL_RESERVED() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Quest_LIST_TOOL_RESERVED(Quest_LIST_TOOL_RESERVED other) : this() {
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Quest_LIST_TOOL_RESERVED Clone() {
      return new Quest_LIST_TOOL_RESERVED(this);
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Com.Youzu.Got.Config.Quest> _repeated_items_codec
        = pb::FieldCodec.ForMessage(10, global::Com.Youzu.Got.Config.Quest.Parser);
    private readonly pbc::RepeatedField<global::Com.Youzu.Got.Config.Quest> items_ = new pbc::RepeatedField<global::Com.Youzu.Got.Config.Quest>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Com.Youzu.Got.Config.Quest> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Quest_LIST_TOOL_RESERVED);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Quest_LIST_TOOL_RESERVED other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!items_.Equals(other.items_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= items_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      items_.WriteTo(output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_repeated_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Quest_LIST_TOOL_RESERVED other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
