// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: task.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace YFramework.Config {

  /// <summary>Holder for reflection information generated from task.proto</summary>
  public static partial class TaskReflection {

    #region Descriptor
    /// <summary>File descriptor for task.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TaskReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgp0YXNrLnByb3RvEhF5ZnJhbWV3b3JrLmNvbmZpZxoUQ29uZmlnQmFzZVR5",
            "cGUucHJvdG8iyAEKBFRhc2sSCgoCaWQYASABKA0SDAoEbmFtZRgCIAEoCRIQ",
            "CghjYXRlZ29yeRgDIAEoDRIUCgx0YXJnZXRBbW91bnQYBCABKAUSFAoMcmV3",
            "YXJkSXRlbUlkGAUgASgNEhcKD3Jld2FyZEl0ZW1Db3VudBgGIAEoBRISCgpy",
            "ZXdhcmRDb2luGAcgASgFEhQKDHNvcnRQcmlvcml0eRgIIAEoBRIUCgxyZXdh",
            "cmRFbmVyZ3kYCSABKAUSDwoHb2JqVHlwZRgKIAEoDSJBChdUYXNrX0xJU1Rf",
            "VE9PTF9SRVNFUlZFRBImCgVpdGVtcxgBIAMoCzIXLnlmcmFtZXdvcmsuY29u",
            "ZmlnLlRhc2tCFKoCEVlGcmFtZXdvcmsuQ29uZmlnYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::YFramework.Config.ConfigBaseTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::YFramework.Config.Task), global::YFramework.Config.Task.Parser, new[]{ "Id", "Name", "Category", "TargetAmount", "RewardItemId", "RewardItemCount", "RewardCoin", "SortPriority", "RewardEnergy", "ObjType" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::YFramework.Config.Task_LIST_TOOL_RESERVED), global::YFramework.Config.Task_LIST_TOOL_RESERVED.Parser, new[]{ "Items" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Task : pb::IMessage<Task> {
    private static readonly pb::MessageParser<Task> _parser = new pb::MessageParser<Task>(() => new Task());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Task> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::YFramework.Config.TaskReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Task() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Task(Task other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      category_ = other.category_;
      targetAmount_ = other.targetAmount_;
      rewardItemId_ = other.rewardItemId_;
      rewardItemCount_ = other.rewardItemCount_;
      rewardCoin_ = other.rewardCoin_;
      sortPriority_ = other.sortPriority_;
      rewardEnergy_ = other.rewardEnergy_;
      objType_ = other.objType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Task Clone() {
      return new Task(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private uint id_;
    /// <summary>
    ///任务ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    /// <summary>
    ///名称
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "category" field.</summary>
    public const int CategoryFieldNumber = 3;
    private uint category_;
    /// <summary>
    ///分类
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Category {
      get { return category_; }
      set {
        category_ = value;
      }
    }

    /// <summary>Field number for the "targetAmount" field.</summary>
    public const int TargetAmountFieldNumber = 4;
    private int targetAmount_;
    /// <summary>
    ///目标进度
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TargetAmount {
      get { return targetAmount_; }
      set {
        targetAmount_ = value;
      }
    }

    /// <summary>Field number for the "rewardItemId" field.</summary>
    public const int RewardItemIdFieldNumber = 5;
    private uint rewardItemId_;
    /// <summary>
    ///奖励物品ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint RewardItemId {
      get { return rewardItemId_; }
      set {
        rewardItemId_ = value;
      }
    }

    /// <summary>Field number for the "rewardItemCount" field.</summary>
    public const int RewardItemCountFieldNumber = 6;
    private int rewardItemCount_;
    /// <summary>
    ///奖励物品数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RewardItemCount {
      get { return rewardItemCount_; }
      set {
        rewardItemCount_ = value;
      }
    }

    /// <summary>Field number for the "rewardCoin" field.</summary>
    public const int RewardCoinFieldNumber = 7;
    private int rewardCoin_;
    /// <summary>
    ///奖励金币
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RewardCoin {
      get { return rewardCoin_; }
      set {
        rewardCoin_ = value;
      }
    }

    /// <summary>Field number for the "sortPriority" field.</summary>
    public const int SortPriorityFieldNumber = 8;
    private int sortPriority_;
    /// <summary>
    ///排序权重
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SortPriority {
      get { return sortPriority_; }
      set {
        sortPriority_ = value;
      }
    }

    /// <summary>Field number for the "rewardEnergy" field.</summary>
    public const int RewardEnergyFieldNumber = 9;
    private int rewardEnergy_;
    /// <summary>
    ///奖励体力
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RewardEnergy {
      get { return rewardEnergy_; }
      set {
        rewardEnergy_ = value;
      }
    }

    /// <summary>Field number for the "objType" field.</summary>
    public const int ObjTypeFieldNumber = 10;
    private uint objType_;
    /// <summary>
    ///任务类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ObjType {
      get { return objType_; }
      set {
        objType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Task);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Task other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (Category != other.Category) return false;
      if (TargetAmount != other.TargetAmount) return false;
      if (RewardItemId != other.RewardItemId) return false;
      if (RewardItemCount != other.RewardItemCount) return false;
      if (RewardCoin != other.RewardCoin) return false;
      if (SortPriority != other.SortPriority) return false;
      if (RewardEnergy != other.RewardEnergy) return false;
      if (ObjType != other.ObjType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Category != 0) hash ^= Category.GetHashCode();
      if (TargetAmount != 0) hash ^= TargetAmount.GetHashCode();
      if (RewardItemId != 0) hash ^= RewardItemId.GetHashCode();
      if (RewardItemCount != 0) hash ^= RewardItemCount.GetHashCode();
      if (RewardCoin != 0) hash ^= RewardCoin.GetHashCode();
      if (SortPriority != 0) hash ^= SortPriority.GetHashCode();
      if (RewardEnergy != 0) hash ^= RewardEnergy.GetHashCode();
      if (ObjType != 0) hash ^= ObjType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Category != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Category);
      }
      if (TargetAmount != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(TargetAmount);
      }
      if (RewardItemId != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(RewardItemId);
      }
      if (RewardItemCount != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(RewardItemCount);
      }
      if (RewardCoin != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(RewardCoin);
      }
      if (SortPriority != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(SortPriority);
      }
      if (RewardEnergy != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(RewardEnergy);
      }
      if (ObjType != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(ObjType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Category != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Category);
      }
      if (TargetAmount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TargetAmount);
      }
      if (RewardItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RewardItemId);
      }
      if (RewardItemCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RewardItemCount);
      }
      if (RewardCoin != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RewardCoin);
      }
      if (SortPriority != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SortPriority);
      }
      if (RewardEnergy != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RewardEnergy);
      }
      if (ObjType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ObjType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Task other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Category != 0) {
        Category = other.Category;
      }
      if (other.TargetAmount != 0) {
        TargetAmount = other.TargetAmount;
      }
      if (other.RewardItemId != 0) {
        RewardItemId = other.RewardItemId;
      }
      if (other.RewardItemCount != 0) {
        RewardItemCount = other.RewardItemCount;
      }
      if (other.RewardCoin != 0) {
        RewardCoin = other.RewardCoin;
      }
      if (other.SortPriority != 0) {
        SortPriority = other.SortPriority;
      }
      if (other.RewardEnergy != 0) {
        RewardEnergy = other.RewardEnergy;
      }
      if (other.ObjType != 0) {
        ObjType = other.ObjType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadUInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Category = input.ReadUInt32();
            break;
          }
          case 32: {
            TargetAmount = input.ReadInt32();
            break;
          }
          case 40: {
            RewardItemId = input.ReadUInt32();
            break;
          }
          case 48: {
            RewardItemCount = input.ReadInt32();
            break;
          }
          case 56: {
            RewardCoin = input.ReadInt32();
            break;
          }
          case 64: {
            SortPriority = input.ReadInt32();
            break;
          }
          case 72: {
            RewardEnergy = input.ReadInt32();
            break;
          }
          case 80: {
            ObjType = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Task_LIST_TOOL_RESERVED : pb::IMessage<Task_LIST_TOOL_RESERVED> {
    private static readonly pb::MessageParser<Task_LIST_TOOL_RESERVED> _parser = new pb::MessageParser<Task_LIST_TOOL_RESERVED>(() => new Task_LIST_TOOL_RESERVED());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Task_LIST_TOOL_RESERVED> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::YFramework.Config.TaskReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Task_LIST_TOOL_RESERVED() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Task_LIST_TOOL_RESERVED(Task_LIST_TOOL_RESERVED other) : this() {
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Task_LIST_TOOL_RESERVED Clone() {
      return new Task_LIST_TOOL_RESERVED(this);
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::YFramework.Config.Task> _repeated_items_codec
        = pb::FieldCodec.ForMessage(10, global::YFramework.Config.Task.Parser);
    private readonly pbc::RepeatedField<global::YFramework.Config.Task> items_ = new pbc::RepeatedField<global::YFramework.Config.Task>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::YFramework.Config.Task> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Task_LIST_TOOL_RESERVED);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Task_LIST_TOOL_RESERVED other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!items_.Equals(other.items_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= items_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      items_.WriteTo(output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_repeated_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Task_LIST_TOOL_RESERVED other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
