# gtp/writer/CSWriter.py

import os
from gtp.common.ConfigData import ConfigData
from gtp.writer import ProtoHelper

NAMESPACE = "YFramework.Config"
MANAGER_CLASS = "ConfigManager"
BASE_CLASS = "ConfigBase"


def _snakeToPascal(name: str) -> str:
    """snake_case -> PascalCase (protoc C# 命名规则)"""
    return "".join(part.capitalize() for part in name.split("_"))

# ==================== 基类模板 ====================
TEMPLATE_BASE = '''/**
 * Generated By Tool, DO NOT MODIFY.
**/

using System.IO;
using Google.Protobuf;
using UnityEngine;

namespace {namespace}
{{
    public abstract class {baseClass}
    {{
        private const string CONFIG_PATH = "Config/Data/";

        protected byte[] LoadConfigBytes(string name)
        {{
            var asset = Resources.Load<TextAsset>(CONFIG_PATH + name);
            if (asset == null)
            {{
                Debug.LogError($"[Config] Failed to load config: {{name}}");
                return null;
            }}
            return asset.bytes;
        }}

        protected T Deserialize<T>(MemoryStream ms) where T : IMessage<T>, new()
        {{
            var parser = new MessageParser<T>(() => new T());
            return parser.ParseFrom(ms);
        }}
    }}

    public partial class {managerClass}
    {{
    }}
}}
'''

# ==================== 单键模板 ====================
TEMPLATE_SINGLE_KEY = '''/**
 * Generated By Tool, DO NOT MODIFY.
**/

using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

namespace {namespace}
{{
    public partial class {configClass} : {baseClass}
    {{
        public bool isLoaded;
        private Dictionary<{keyType}, {protoClass}> m_items = null;

        public Dictionary<{keyType}, {protoClass}> items
        {{
            get
            {{
                Load();
                return m_items;
            }}
        }}

        public void Load()
        {{
            if (isLoaded) return;
            m_items = new Dictionary<{keyType}, {protoClass}>();
            isLoaded = true;

            var bytes = LoadConfigBytes("{bytesName}");
            if (bytes != null)
            {{
                using (var ms = new MemoryStream(bytes))
                {{
                    var list = Deserialize<{protoClass}_LIST_TOOL_RESERVED>(ms);
                    foreach (var item in list.Items)
                    {{
                        m_items[item.{keyField}] = item;
                    }}
                }}
            }}
        }}

        public {protoClass} Get({keyType} key)
        {{
            Load();
            {protoClass} item = null;
            items.TryGetValue(key, out item);
            return item;
        }}
    }}

    public partial class {managerClass}
    {{
        private {configClass} m_{configVar};
        public {configClass} {configVar}
        {{
            get
            {{
                if (m_{configVar} == null) m_{configVar} = new {configClass}();
                return m_{configVar};
            }}
        }}
    }}
}}
'''

# ==================== 双键子类模板 (Tree) ====================
TEMPLATE_DOUBLE_KEY_CLASS = '''public class C{protoClass}
    {{
        public Dictionary<{keyType2}, {protoClass}> items = new Dictionary<{keyType2}, {protoClass}>();
        public {protoClass} main;

        public {protoClass} Get({keyType2} key)
        {{
            {protoClass} item = null;
            items.TryGetValue(key, out item);
            return item;
        }}
    }}'''

# ==================== 双键模板 (Tree) ====================
TEMPLATE_DOUBLE_KEY_TREE = '''/**
 * Generated By Tool, DO NOT MODIFY.
**/

using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

namespace {namespace}
{{
    {subclass}

    public partial class {configClass} : {baseClass}
    {{
        public bool isLoaded;
        private Dictionary<{keyType1}, Dictionary<{keyType2}, {protoClass}>> m_items = null;
        private Dictionary<{keyType1}, C{protoClass}> m_citems = null;

        public Dictionary<{keyType1}, Dictionary<{keyType2}, {protoClass}>> items
        {{
            get {{ Load(); return m_items; }}
        }}

        public Dictionary<{keyType1}, C{protoClass}> citems
        {{
            get {{ Load(); return m_citems; }}
        }}

        public void Load()
        {{
            if (isLoaded) return;
            m_items = new Dictionary<{keyType1}, Dictionary<{keyType2}, {protoClass}>>();
            m_citems = new Dictionary<{keyType1}, C{protoClass}>();
            isLoaded = true;

            var bytes = LoadConfigBytes("{bytesName}");
            if (bytes != null)
            {{
                using (var ms = new MemoryStream(bytes))
                {{
                    var list = Deserialize<{protoClass}_LIST_TOOL_RESERVED>(ms);
                    foreach (var item in list.Items)
                    {{
                        Dictionary<{keyType2}, {protoClass}> sd = null;
                        if (!m_items.TryGetValue(item.{keyField1}, out sd))
                        {{
                            sd = new Dictionary<{keyType2}, {protoClass}>();
                            m_items[item.{keyField1}] = sd;
                        }}
                        sd[item.{keyField2}] = item;

                        if (!m_citems.ContainsKey(item.{keyField1}))
                        {{
                            var ci = new C{protoClass}();
                            ci.items = sd;
                            ci.main = item;
                            m_citems[item.{keyField1}] = ci;
                        }}
                    }}
                }}
            }}
        }}

        public Dictionary<{keyType2}, {protoClass}> Get({keyType1} key)
        {{
            Load();
            Dictionary<{keyType2}, {protoClass}> item = null;
            items.TryGetValue(key, out item);
            return item;
        }}

        public C{protoClass} GetId({keyType1} key)
        {{
            Load();
            C{protoClass} item = null;
            citems.TryGetValue(key, out item);
            return item;
        }}

        public {protoClass} Get({keyType1} key1, {keyType2} key2)
        {{
            Load();
            var d = Get(key1);
            if (d != null)
            {{
                {protoClass} item = null;
                d.TryGetValue(key2, out item);
                return item;
            }}
            return null;
        }}
    }}

    public partial class {managerClass}
    {{
        private {configClass} m_{configVar};
        public {configClass} {configVar}
        {{
            get
            {{
                if (m_{configVar} == null) m_{configVar} = new {configClass}();
                return m_{configVar};
            }}
        }}
    }}
}}
'''

# ==================== 双键模板 (Row, 第二键为自增 int) ====================
TEMPLATE_DOUBLE_KEY_ROW_CLASS = '''public class C{protoClass}
    {{
        public Dictionary<int, {protoClass}> items = new Dictionary<int, {protoClass}>();
        public {protoClass} main;

        public {protoClass} Get(int key)
        {{
            {protoClass} item = null;
            items.TryGetValue(key, out item);
            return item;
        }}
    }}'''

TEMPLATE_DOUBLE_KEY_ROW = '''/**
 * Generated By Tool, DO NOT MODIFY.
**/

using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

namespace {namespace}
{{
    {subclass}

    public partial class {configClass} : {baseClass}
    {{
        public bool isLoaded;
        private Dictionary<{keyType1}, Dictionary<int, {protoClass}>> m_items = null;
        private Dictionary<{keyType1}, C{protoClass}> m_citems = null;

        public Dictionary<{keyType1}, Dictionary<int, {protoClass}>> items
        {{
            get {{ Load(); return m_items; }}
        }}

        public void Load()
        {{
            if (isLoaded) return;
            m_items = new Dictionary<{keyType1}, Dictionary<int, {protoClass}>>();
            m_citems = new Dictionary<{keyType1}, C{protoClass}>();
            isLoaded = true;

            var bytes = LoadConfigBytes("{bytesName}");
            if (bytes != null)
            {{
                using (var ms = new MemoryStream(bytes))
                {{
                    var list = Deserialize<{protoClass}_LIST_TOOL_RESERVED>(ms);
                    foreach (var item in list.Items)
                    {{
                        Dictionary<int, {protoClass}> sd = null;
                        if (!m_items.TryGetValue(item.{keyField1}, out sd))
                        {{
                            sd = new Dictionary<int, {protoClass}>();
                            m_items[item.{keyField1}] = sd;
                        }}
                        sd[sd.Count + 1] = item;

                        if (!m_citems.ContainsKey(item.{keyField1}))
                        {{
                            var ci = new C{protoClass}();
                            ci.items = sd;
                            ci.main = item;
                            m_citems[item.{keyField1}] = ci;
                        }}
                    }}
                }}
            }}
        }}

        public Dictionary<int, {protoClass}> Get({keyType1} key)
        {{
            Load();
            Dictionary<int, {protoClass}> item = null;
            items.TryGetValue(key, out item);
            return item;
        }}

        public {protoClass} Get({keyType1} key1, int key2)
        {{
            Load();
            var d = Get(key1);
            if (d != null)
            {{
                {protoClass} item = null;
                d.TryGetValue(key2, out item);
                return item;
            }}
            return null;
        }}
    }}

    public partial class {managerClass}
    {{
        private {configClass} m_{configVar};
        public {configClass} {configVar}
        {{
            get
            {{
                if (m_{configVar} == null) m_{configVar} = new {configClass}();
                return m_{configVar};
            }}
        }}
    }}
}}
'''


def writeBaseClass(dirPath: str) -> str:
    """生成 ConfigBase.cs 基类，返回文件路径"""
    path = os.path.join(dirPath, f"{BASE_CLASS}.cs")
    content = TEMPLATE_BASE.format(
        namespace=NAMESPACE,
        baseClass=BASE_CLASS,
        managerClass=MANAGER_CLASS,
    )
    os.makedirs(dirPath, exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    return path


def writeData(path: str, data: ConfigData) -> bool:
    """根据索引键数量选择模板，生成 C# 配置类"""
    colCount = len(data.colID)
    if colCount <= 0 or not data.dataIndex:
        return False

    protoClass = data.id[0].upper() + data.id[1:]

    fmt: dict[str, str] = {
        "namespace":    NAMESPACE,
        "baseClass":    BASE_CLASS,
        "configClass":  f"{protoClass}Config",
        "configVar":    f"{data.id[0].lower()}{data.id[1:]}Config",
        "protoClass":   protoClass,
        "managerClass": MANAGER_CLASS,
        "bytesName":    protoClass,
    }

    keyCount = len(data.dataIndex[0])

    if keyCount <= 1:
        # ---- 单键 ----
        keyName = data.dataIndex[0][0]
        if keyName not in data.colID:
            raise ValueError(f"键列 '{keyName}' 不在列定义中: {data.colID}")
        keyColType = data.colType[data.colID.index(keyName)]
        fmt["keyType"] = ProtoHelper.getProtoType(keyColType).replace("32", "")
        fmt["keyField"] = _snakeToPascal(keyName)
        content = TEMPLATE_SINGLE_KEY.format(**fmt)

    else:
        # ---- 双键 ----
        keyName1 = data.dataIndex[0][0]
        keyName2 = data.dataIndex[0][1]
        if keyName1 not in data.colID:
            raise ValueError(f"主键列 '{keyName1}' 不在列定义中: {data.colID}")
        if keyName2 not in data.colID:
            raise ValueError(f"副键列 '{keyName2}' 不在列定义中: {data.colID}")
        keyColType1 = data.colType[data.colID.index(keyName1)]
        keyColType2 = data.colType[data.colID.index(keyName2)]
        fmt["keyType1"] = ProtoHelper.getProtoType(keyColType1).replace("32", "")
        fmt["keyType2"] = ProtoHelper.getProtoType(keyColType2).replace("32", "")
        fmt["keyField1"] = _snakeToPascal(keyName1)
        fmt["keyField2"] = _snakeToPascal(keyName2)

        if "R" in data.ext:
            # Row 模式：第二键为自增 int
            fmt["subclass"] = TEMPLATE_DOUBLE_KEY_ROW_CLASS.format(**fmt)
            content = TEMPLATE_DOUBLE_KEY_ROW.format(**fmt)
        else:
            # Tree 模式
            fmt["subclass"] = TEMPLATE_DOUBLE_KEY_CLASS.format(**fmt)
            content = TEMPLATE_DOUBLE_KEY_TREE.format(**fmt)

    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    return True
