# gtp/writer/ProtoWriter.py

from gtp.common.ConfigData import ConfigData
from gtp.writer import ProtoHelper

# ---- 基础类型定义（只需生成一次） ----
PROTO_BASE_TYPES = '''/**
 * Generated By Tool, DO NOT MODIFY.
**/
syntax = "proto3";
package com.youzu.got.config;

message Vector2Int {
  int32 x = 1;
  int32 y = 2;
}
message Vector3Int {
  int32 x = 1;
  int32 y = 2;
  int32 z = 3;
}
message Vector2Float {
  float x = 1;
  float y = 2;
}
message Vector3Float {
  float x = 1;
  float y = 2;
  float z = 3;
}
message KeyValuePairStrInt {
  string k = 1;
  int32 v = 2;
}
message KeyValuePairStrFloat {
  string k = 1;
  float v = 2;
}

// ---- Header 索引类型（用于新版懒加载） ----
message IndexInt {
  int32 id = 1;
  int32 offset = 2;
}
message ConfigIntHeader {
  repeated IndexInt headers = 1;
}
message IndexUint {
  uint32 id = 1;
  int32 offset = 2;
}
message ConfigUintHeader {
  repeated IndexUint headers = 1;
}
message IndexStr {
  string id = 1;
  int32 offset = 2;
}
message ConfigStringHeader {
  repeated IndexStr headers = 1;
}
'''


def writeBaseTypes(path: str) -> None:
    """生成 ConfigBaseType.proto"""
    with open(path, 'w', encoding='utf-8') as f:
        f.write(PROTO_BASE_TYPES)


def writeData(path: str, data: ConfigData) -> bool:
    """为一张配置表生成 .proto 文件"""
    colCount = len(data.colID)
    if colCount <= 0:
        return False

    className = data.id[0].upper() + data.id[1:]
    package = "com.youzu.got.config"

    lines: list[str] = [
        '/**\n * Generated by tools, don\'t modify!\n**/',
        'syntax = "proto3";',
        f'package {package};\n',
        'import "ConfigBaseType.proto";\n',
        f'message {className} {{',
    ]

    for i in range(colCount):
        rule = ProtoHelper.getProtoRule(data.colType[i])
        ptype = ProtoHelper.getProtoType(data.colType[i])
        prefix = f"{rule} {ptype}" if rule else ptype
        lines.append(f'  {prefix} {data.colID[i]} = {i + 1}; //{data.colName[i]}')

    lines.append('}\n')

    # LIST 包装消息（用于序列化整张表）
    lines.append(f'message {className}_LIST_TOOL_RESERVED {{')
    lines.append(f'  repeated {className} items = 1;')
    lines.append('}')

    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    return True
