"""
Generated by excel-generation skill, DO NOT MODIFY by hand.
若需调整列结构：先改对应配表规划文档（升 v 进位），再重跑 /excel-generation。

excel_plan_doc: 配表规划/System/Bag/SYS-Bag-Excel-v1.md
source_doc:     策划案/System/Bag/SYS-Bag-v1.md
plan_doc:       代码规划/System/Bag/SYS-Bag-Plan-v1.md
created:        2026-05-10
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _helpers import build_xlsx

TABLE_NAME = "item"
OUT_PATH = os.path.normpath(os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..", "..", "excel", "3xlsx", TABLE_NAME + ".xlsx",
))

COLUMNS = [
    {"col_name": "物品ID",   "col_id": "id",           "type": "uint",   "target": "client_key", "ext": "", "default": "0"},
    {"col_name": "名称",     "col_id": "name",         "type": "string", "target": "client",     "ext": "", "default": ""},
    {"col_name": "描述",     "col_id": "desc",         "type": "string", "target": "client",     "ext": "", "default": ""},
    {"col_name": "类型",     "col_id": "type",         "type": "uint",   "target": "client",     "ext": "", "default": "0"},
    {"col_name": "图标路径", "col_id": "iconPath",     "type": "string", "target": "client",     "ext": "", "default": ""},
    {"col_name": "堆叠上限", "col_id": "maxStack",     "type": "int",    "target": "client",     "ext": "", "default": "99"},
    {"col_name": "排序权重", "col_id": "sortPriority", "type": "int",    "target": "client",     "ext": "", "default": "0"},
]

ROWS = [
    [1001, "占位道具A",     "这是一个用于联调的占位道具。", 0, "UI/Item/1001",     99, 0],
    [2001, "占位材料A",     "用于联调材料分类。",           1, "UI/Item/2001",     99, 0],
    [3001, "占位任务物品A", "用于联调任务物品分类。",       2, "UI/Item/3001",     99, 0],
    [9001, "金币",          "通用货币。",                   3, "UI/Currency/9001", 99, 0],
]

IS_TREE = False


if __name__ == "__main__":
    if os.path.exists(OUT_PATH):
        print(f"[excel-generation] REFUSE: {OUT_PATH} 已存在，不覆盖。手工 rm 后再跑或走修改型流程。")
        sys.exit(2)
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    p = build_xlsx(OUT_PATH, TABLE_NAME, COLUMNS, ROWS, IS_TREE)
    print(f"[excel-generation] WROTE {p}")
