/**
 * Generated By Tool, DO NOT MODIFY.
**/

using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

namespace YFramework.Config
{
    public partial class AnimalConfig : ConfigBase
    {
        public bool isLoaded;
        private Dictionary<uint, Animal> m_items = null;

        public Dictionary<uint, Animal> items
        {
            get
            {
                Load();
                return m_items;
            }
        }

        public void Load()
        {
            if (isLoaded) return;
            m_items = new Dictionary<uint, Animal>();
            isLoaded = true;

            var bytes = LoadConfigBytes("Animal");
            if (bytes != null)
            {
                using (var ms = new MemoryStream(bytes))
                {
                    var list = Deserialize<Animal_LIST_TOOL_RESERVED>(ms);
                    foreach (var item in list.Items)
                    {
                        m_items[item.Id] = item;
                    }
                }
            }
        }

        public Animal Get(uint key)
        {
            Load();
            Animal item = null;
            items.TryGetValue(key, out item);
            return item;
        }
    }

    public partial class ConfigManager
    {
        private AnimalConfig m_animalConfig;
        public AnimalConfig animalConfig
        {
            get
            {
                if (m_animalConfig == null) m_animalConfig = new AnimalConfig();
                return m_animalConfig;
            }
        }
    }
}
