/**
 * Generated By Tool, DO NOT MODIFY.
**/

using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

namespace YFramework.Config
{
    public partial class ChestDropConfig : ConfigBase
    {
        public bool isLoaded;
        private Dictionary<uint, ChestDrop> m_items = null;

        public Dictionary<uint, ChestDrop> items
        {
            get
            {
                Load();
                return m_items;
            }
        }

        public void Load()
        {
            if (isLoaded) return;
            m_items = new Dictionary<uint, ChestDrop>();
            isLoaded = true;

            var bytes = LoadConfigBytes("ChestDrop");
            if (bytes != null)
            {
                using (var ms = new MemoryStream(bytes))
                {
                    var list = Deserialize<ChestDrop_LIST_TOOL_RESERVED>(ms);
                    foreach (var item in list.Items)
                    {
                        m_items[item.Id] = item;
                    }
                }
            }
        }

        public ChestDrop Get(uint key)
        {
            Load();
            ChestDrop item = null;
            items.TryGetValue(key, out item);
            return item;
        }
    }

    public partial class ConfigManager
    {
        private ChestDropConfig m_chestDropConfig;
        public ChestDropConfig chestDropConfig
        {
            get
            {
                if (m_chestDropConfig == null) m_chestDropConfig = new ChestDropConfig();
                return m_chestDropConfig;
            }
        }
    }
}
