/**
 * Generated By Tool, DO NOT MODIFY.
**/

using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

namespace YFramework.Config
{
    public partial class ChestConfig : ConfigBase
    {
        public bool isLoaded;
        private Dictionary<uint, Chest> m_items = null;

        public Dictionary<uint, Chest> items
        {
            get
            {
                Load();
                return m_items;
            }
        }

        public void Load()
        {
            if (isLoaded) return;
            m_items = new Dictionary<uint, Chest>();
            isLoaded = true;

            var bytes = LoadConfigBytes("Chest");
            if (bytes != null)
            {
                using (var ms = new MemoryStream(bytes))
                {
                    var list = Deserialize<Chest_LIST_TOOL_RESERVED>(ms);
                    foreach (var item in list.Items)
                    {
                        m_items[item.Id] = item;
                    }
                }
            }
        }

        public Chest Get(uint key)
        {
            Load();
            Chest item = null;
            items.TryGetValue(key, out item);
            return item;
        }
    }

    public partial class ConfigManager
    {
        private ChestConfig m_chestConfig;
        public ChestConfig chestConfig
        {
            get
            {
                if (m_chestConfig == null) m_chestConfig = new ChestConfig();
                return m_chestConfig;
            }
        }
    }
}
