/**
 * Generated By Tool, DO NOT MODIFY.
**/

using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

namespace YFramework.Config
{
    public partial class CodexConfig : ConfigBase
    {
        public bool isLoaded;
        private Dictionary<uint, Codex> m_items = null;

        public Dictionary<uint, Codex> items
        {
            get
            {
                Load();
                return m_items;
            }
        }

        public void Load()
        {
            if (isLoaded) return;
            m_items = new Dictionary<uint, Codex>();
            isLoaded = true;

            var bytes = LoadConfigBytes("Codex");
            if (bytes != null)
            {
                using (var ms = new MemoryStream(bytes))
                {
                    var list = Deserialize<Codex_LIST_TOOL_RESERVED>(ms);
                    foreach (var item in list.Items)
                    {
                        m_items[item.Id] = item;
                    }
                }
            }
        }

        public Codex Get(uint key)
        {
            Load();
            Codex item = null;
            items.TryGetValue(key, out item);
            return item;
        }
    }

    public partial class ConfigManager
    {
        private CodexConfig m_codexConfig;
        public CodexConfig codexConfig
        {
            get
            {
                if (m_codexConfig == null) m_codexConfig = new CodexConfig();
                return m_codexConfig;
            }
        }
    }
}
