/**
 * Generated By Tool, DO NOT MODIFY.
**/

using System.IO;
using Google.Protobuf;
using UnityEngine;

namespace YFramework.Config
{
    public abstract class ConfigBase
    {
        private const string CONFIG_PATH = "Config/Data/";

        protected byte[] LoadConfigBytes(string name)
        {
            var asset = Resources.Load<TextAsset>(CONFIG_PATH + name);
            if (asset == null)
            {
                Debug.LogError($"[Config] Failed to load config: {name}");
                return null;
            }
            return asset.bytes;
        }

        protected T Deserialize<T>(MemoryStream ms) where T : IMessage<T>, new()
        {
            var parser = new MessageParser<T>(() => new T());
            return parser.ParseFrom(ms);
        }
    }

    public partial class ConfigManager
    {
    }
}
