/**
 * Generated By Tool, DO NOT MODIFY.
**/

using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

namespace YFramework.Config
{
    public partial class CurrencyConfig : ConfigBase
    {
        public bool isLoaded;
        private Dictionary<uint, Currency> m_items = null;

        public Dictionary<uint, Currency> items
        {
            get
            {
                Load();
                return m_items;
            }
        }

        public void Load()
        {
            if (isLoaded) return;
            m_items = new Dictionary<uint, Currency>();
            isLoaded = true;

            var bytes = LoadConfigBytes("Currency");
            if (bytes != null)
            {
                using (var ms = new MemoryStream(bytes))
                {
                    var list = Deserialize<Currency_LIST_TOOL_RESERVED>(ms);
                    foreach (var item in list.Items)
                    {
                        m_items[item.Id] = item;
                    }
                }
            }
        }

        public Currency Get(uint key)
        {
            Load();
            Currency item = null;
            items.TryGetValue(key, out item);
            return item;
        }
    }

    public partial class ConfigManager
    {
        private CurrencyConfig m_currencyConfig;
        public CurrencyConfig currencyConfig
        {
            get
            {
                if (m_currencyConfig == null) m_currencyConfig = new CurrencyConfig();
                return m_currencyConfig;
            }
        }
    }
}
