/**
 * Generated By Tool, DO NOT MODIFY.
**/

using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

namespace Com.Youzu.Got.Config
{
    public partial class HeroConfig : ConfigBase
    {
        public bool isLoaded;
        private Dictionary<uint, Hero> m_items = null;

        public Dictionary<uint, Hero> items
        {
            get
            {
                Load();
                return m_items;
            }
        }

        public void Load()
        {
            if (isLoaded) return;
            m_items = new Dictionary<uint, Hero>();
            isLoaded = true;

            var bytes = LoadConfigBytes("Hero");
            if (bytes != null)
            {
                using (var ms = new MemoryStream(bytes))
                {
                    var list = Deserialize<Hero_LIST_TOOL_RESERVED>(ms);
                    foreach (var item in list.Items)
                    {
                        m_items[item.HeroId] = item;
                    }
                }
            }
        }

        public Hero Get(uint key)
        {
            Load();
            Hero item = null;
            items.TryGetValue(key, out item);
            return item;
        }
    }

    public partial class GotConfigManager
    {
        private HeroConfig m_heroConfig;
        public HeroConfig heroConfig
        {
            get
            {
                if (m_heroConfig == null) m_heroConfig = new HeroConfig();
                return m_heroConfig;
            }
        }
    }
}
