/**
 * Generated By Tool, DO NOT MODIFY.
**/

using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

namespace YFramework.Config
{
    public partial class ItemConfig : ConfigBase
    {
        public bool isLoaded;
        private Dictionary<uint, Item> m_items = null;

        public Dictionary<uint, Item> items
        {
            get
            {
                Load();
                return m_items;
            }
        }

        public void Load()
        {
            if (isLoaded) return;
            m_items = new Dictionary<uint, Item>();
            isLoaded = true;

            var bytes = LoadConfigBytes("Item");
            if (bytes != null)
            {
                using (var ms = new MemoryStream(bytes))
                {
                    var list = Deserialize<Item_LIST_TOOL_RESERVED>(ms);
                    foreach (var item in list.Items)
                    {
                        m_items[item.Id] = item;
                    }
                }
            }
        }

        public Item Get(uint key)
        {
            Load();
            Item item = null;
            items.TryGetValue(key, out item);
            return item;
        }
    }

    public partial class ConfigManager
    {
        private ItemConfig m_itemConfig;
        public ItemConfig itemConfig
        {
            get
            {
                if (m_itemConfig == null) m_itemConfig = new ItemConfig();
                return m_itemConfig;
            }
        }
    }
}
