/**
 * Generated By Tool, DO NOT MODIFY.
**/

using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

namespace YFramework.Config
{
    public partial class MapConfig : ConfigBase
    {
        public bool isLoaded;
        private Dictionary<uint, Map> m_items = null;

        public Dictionary<uint, Map> items
        {
            get
            {
                Load();
                return m_items;
            }
        }

        public void Load()
        {
            if (isLoaded) return;
            m_items = new Dictionary<uint, Map>();
            isLoaded = true;

            var bytes = LoadConfigBytes("Map");
            if (bytes != null)
            {
                using (var ms = new MemoryStream(bytes))
                {
                    var list = Deserialize<Map_LIST_TOOL_RESERVED>(ms);
                    foreach (var item in list.Items)
                    {
                        m_items[item.Id] = item;
                    }
                }
            }
        }

        public Map Get(uint key)
        {
            Load();
            Map item = null;
            items.TryGetValue(key, out item);
            return item;
        }
    }

    public partial class ConfigManager
    {
        private MapConfig m_mapConfig;
        public MapConfig mapConfig
        {
            get
            {
                if (m_mapConfig == null) m_mapConfig = new MapConfig();
                return m_mapConfig;
            }
        }
    }
}
