/**
 * Generated By Tool, DO NOT MODIFY.
**/

using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

namespace Com.Youzu.Got.Config
{
    public class CQuest
    {
        public Dictionary<uint, Quest> items = new Dictionary<uint, Quest>();
        public Quest main;

        public Quest Get(uint key)
        {
            Quest item = null;
            items.TryGetValue(key, out item);
            return item;
        }
    }

    public partial class QuestConfig : ConfigBase
    {
        public bool isLoaded;
        private Dictionary<uint, Dictionary<uint, Quest>> m_items = null;
        private Dictionary<uint, CQuest> m_citems = null;

        public Dictionary<uint, Dictionary<uint, Quest>> items
        {
            get { Load(); return m_items; }
        }

        public Dictionary<uint, CQuest> citems
        {
            get { Load(); return m_citems; }
        }

        public void Load()
        {
            if (isLoaded) return;
            m_items = new Dictionary<uint, Dictionary<uint, Quest>>();
            m_citems = new Dictionary<uint, CQuest>();
            isLoaded = true;

            var bytes = LoadConfigBytes("Quest");
            if (bytes != null)
            {
                using (var ms = new MemoryStream(bytes))
                {
                    var list = Deserialize<Quest_LIST_TOOL_RESERVED>(ms);
                    foreach (var item in list.Items)
                    {
                        Dictionary<uint, Quest> sd = null;
                        if (!m_items.TryGetValue(item.QuestId, out sd))
                        {
                            sd = new Dictionary<uint, Quest>();
                            m_items[item.QuestId] = sd;
                        }
                        sd[item.StepId] = item;

                        if (!m_citems.ContainsKey(item.QuestId))
                        {
                            var ci = new CQuest();
                            ci.items = sd;
                            ci.main = item;
                            m_citems[item.QuestId] = ci;
                        }
                    }
                }
            }
        }

        public Dictionary<uint, Quest> Get(uint key)
        {
            Load();
            Dictionary<uint, Quest> item = null;
            items.TryGetValue(key, out item);
            return item;
        }

        public CQuest GetId(uint key)
        {
            Load();
            CQuest item = null;
            citems.TryGetValue(key, out item);
            return item;
        }

        public Quest Get(uint key1, uint key2)
        {
            Load();
            var d = Get(key1);
            if (d != null)
            {
                Quest item = null;
                d.TryGetValue(key2, out item);
                return item;
            }
            return null;
        }
    }

    public partial class GotConfigManager
    {
        private QuestConfig m_questConfig;
        public QuestConfig questConfig
        {
            get
            {
                if (m_questConfig == null) m_questConfig = new QuestConfig();
                return m_questConfig;
            }
        }
    }
}
