/**
 * Generated By Tool, DO NOT MODIFY.
**/

using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

namespace YFramework.Config
{
    public class CSkill
    {
        public Dictionary<uint, Skill> items = new Dictionary<uint, Skill>();
        public Skill main;

        public Skill Get(uint key)
        {
            Skill item = null;
            items.TryGetValue(key, out item);
            return item;
        }
    }

    public partial class SkillConfig : ConfigBase
    {
        public bool isLoaded;
        private Dictionary<uint, Dictionary<uint, Skill>> m_items = null;
        private Dictionary<uint, CSkill> m_citems = null;

        public Dictionary<uint, Dictionary<uint, Skill>> items
        {
            get { Load(); return m_items; }
        }

        public Dictionary<uint, CSkill> citems
        {
            get { Load(); return m_citems; }
        }

        public void Load()
        {
            if (isLoaded) return;
            m_items = new Dictionary<uint, Dictionary<uint, Skill>>();
            m_citems = new Dictionary<uint, CSkill>();
            isLoaded = true;

            var bytes = LoadConfigBytes("Skill");
            if (bytes != null)
            {
                using (var ms = new MemoryStream(bytes))
                {
                    var list = Deserialize<Skill_LIST_TOOL_RESERVED>(ms);
                    foreach (var item in list.Items)
                    {
                        Dictionary<uint, Skill> sd = null;
                        if (!m_items.TryGetValue(item.HeroId, out sd))
                        {
                            sd = new Dictionary<uint, Skill>();
                            m_items[item.HeroId] = sd;
                        }
                        sd[item.SkillId] = item;

                        if (!m_citems.ContainsKey(item.HeroId))
                        {
                            var ci = new CSkill();
                            ci.items = sd;
                            ci.main = item;
                            m_citems[item.HeroId] = ci;
                        }
                    }
                }
            }
        }

        public Dictionary<uint, Skill> Get(uint key)
        {
            Load();
            Dictionary<uint, Skill> item = null;
            items.TryGetValue(key, out item);
            return item;
        }

        public CSkill GetId(uint key)
        {
            Load();
            CSkill item = null;
            citems.TryGetValue(key, out item);
            return item;
        }

        public Skill Get(uint key1, uint key2)
        {
            Load();
            var d = Get(key1);
            if (d != null)
            {
                Skill item = null;
                d.TryGetValue(key2, out item);
                return item;
            }
            return null;
        }
    }

    public partial class ConfigManager
    {
        private SkillConfig m_skillConfig;
        public SkillConfig skillConfig
        {
            get
            {
                if (m_skillConfig == null) m_skillConfig = new SkillConfig();
                return m_skillConfig;
            }
        }
    }
}
