/**
 * Generated By Tool, DO NOT MODIFY.
**/

using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

namespace YFramework.Config
{
    public partial class TaskConfig : ConfigBase
    {
        public bool isLoaded;
        private Dictionary<uint, Task> m_items = null;

        public Dictionary<uint, Task> items
        {
            get
            {
                Load();
                return m_items;
            }
        }

        public void Load()
        {
            if (isLoaded) return;
            m_items = new Dictionary<uint, Task>();
            isLoaded = true;

            var bytes = LoadConfigBytes("Task");
            if (bytes != null)
            {
                using (var ms = new MemoryStream(bytes))
                {
                    var list = Deserialize<Task_LIST_TOOL_RESERVED>(ms);
                    foreach (var item in list.Items)
                    {
                        m_items[item.Id] = item;
                    }
                }
            }
        }

        public Task Get(uint key)
        {
            Load();
            Task item = null;
            items.TryGetValue(key, out item);
            return item;
        }
    }

    public partial class ConfigManager
    {
        private TaskConfig m_taskConfig;
        public TaskConfig taskConfig
        {
            get
            {
                if (m_taskConfig == null) m_taskConfig = new TaskConfig();
                return m_taskConfig;
            }
        }
    }
}
